package com.yidianpuzi.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_priority
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Priority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.priority_name
     *
     * @mbg.generated
     */
    private String priorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.priorty_url
     *
     * @mbg.generated
     */
    private String priortyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.parent
     *
     * @mbg.generated
     */
    private Long parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.create_user
     *
     * @mbg.generated
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_priority.update_user
     *
     * @mbg.generated
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_priority
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.id
     *
     * @return the value of t_priority.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.id
     *
     * @param id the value for t_priority.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.priority_name
     *
     * @return the value of t_priority.priority_name
     *
     * @mbg.generated
     */
    public String getPriorityName() {
        return priorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.priority_name
     *
     * @param priorityName the value for t_priority.priority_name
     *
     * @mbg.generated
     */
    public void setPriorityName(String priorityName) {
        this.priorityName = priorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.priorty_url
     *
     * @return the value of t_priority.priorty_url
     *
     * @mbg.generated
     */
    public String getPriortyUrl() {
        return priortyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.priorty_url
     *
     * @param priortyUrl the value for t_priority.priorty_url
     *
     * @mbg.generated
     */
    public void setPriortyUrl(String priortyUrl) {
        this.priortyUrl = priortyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.type
     *
     * @return the value of t_priority.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.type
     *
     * @param type the value for t_priority.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.parent
     *
     * @return the value of t_priority.parent
     *
     * @mbg.generated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.parent
     *
     * @param parent the value for t_priority.parent
     *
     * @mbg.generated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.remarks
     *
     * @return the value of t_priority.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.remarks
     *
     * @param remarks the value for t_priority.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.create_time
     *
     * @return the value of t_priority.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.create_time
     *
     * @param createTime the value for t_priority.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.create_user
     *
     * @return the value of t_priority.create_user
     *
     * @mbg.generated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.create_user
     *
     * @param createUser the value for t_priority.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.update_time
     *
     * @return the value of t_priority.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.update_time
     *
     * @param updateTime the value for t_priority.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_priority.update_user
     *
     * @return the value of t_priority.update_user
     *
     * @mbg.generated
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_priority.update_user
     *
     * @param updateUser the value for t_priority.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}

