package com.yidianpuzi.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_role_priority
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RolePriority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.priority_id
     *
     * @mbg.generated
     */
    private Long priorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.create_user
     *
     * @mbg.generated
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_priority.update_user
     *
     * @mbg.generated
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_priority
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.id
     *
     * @return the value of t_role_priority.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.id
     *
     * @param id the value for t_role_priority.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.role_id
     *
     * @return the value of t_role_priority.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.role_id
     *
     * @param roleId the value for t_role_priority.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.priority_id
     *
     * @return the value of t_role_priority.priority_id
     *
     * @mbg.generated
     */
    public Long getPriorityId() {
        return priorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.priority_id
     *
     * @param priorityId the value for t_role_priority.priority_id
     *
     * @mbg.generated
     */
    public void setPriorityId(Long priorityId) {
        this.priorityId = priorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.remarks
     *
     * @return the value of t_role_priority.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.remarks
     *
     * @param remarks the value for t_role_priority.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.create_time
     *
     * @return the value of t_role_priority.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.create_time
     *
     * @param createTime the value for t_role_priority.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.create_user
     *
     * @return the value of t_role_priority.create_user
     *
     * @mbg.generated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.create_user
     *
     * @param createUser the value for t_role_priority.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.update_time
     *
     * @return the value of t_role_priority.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.update_time
     *
     * @param updateTime the value for t_role_priority.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_priority.update_user
     *
     * @return the value of t_role_priority.update_user
     *
     * @mbg.generated
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_priority.update_user
     *
     * @param updateUser the value for t_role_priority.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}