package com.yidianpuzi.mapper;

import com.yidianpuzi.domain.Passport;

public interface PassportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    int insert(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    int insertSelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    Passport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Passport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_passport
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Passport record);
}